### ISSUE TITLE
Error: Not found

### ISSUE THREAD

**Issue by Pines-Cheng** [whistle-plugins/whistle.vase#7]
按照 readme 配置，有报错，原因未知：

Error: Not found
    at render (/usr/local/lib/node_modules/whistle.vase/lib/server.js:29:21)
    at /usr/local/lib/node_modules/whistle.vase/lib/server.js:78:3
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/whistle.vase/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/whistle.vase/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/lib/node_modules/whistle.vase/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/lib/node_modules/whistle.vase/node_modules/express/lib/router/index.js:335:12)
    at PassThrough.next (/usr/local/lib/node_modules/whistle.vase/node_modules/express/lib/router/index.js:275:10)
    at emitNone (events.js:111:20)
    at PassThrough.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)

**Comment by echopi** [comment]
配置的 tpl 不存在导致的，你的配置和vase的界面发一下看看

**Comment by echopi** [comment]
比如我新建一个 test-script, rule 应该如下配置

```
www.test.com whistle.vase://test-script
```

**Comment by echopi** [comment]
@Pines-Cheng 系一个兼容代码导致的bug，更新一下试试：
```sh
npm i -g whistle.vase --registry=https://registry.npm.taobao.org
```

**Comment by echopi** [comment]
懒一点可以用，-c 是表示 China

```sh
npm i -g -c whistle.vase

```

**Comment by avwo** [comment]
@echopi Good job，新技能get√

**Comment by Pines-Cheng** [comment]
@echopi TKS
